In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [4]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.4755


In [5]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[2.93683005e-01 2.91528367e-03 2.94888938e-03 6.39103494e-03]
 [1.16643955e-03 8.37905998e-04 3.45835484e-04 1.09842519e-01]
 [1.30032252e-01 3.09081486e-03 1.44642495e-03 3.64574346e-03]
 [7.34445920e-04 5.42881382e-04 6.96369818e-04 4.09922286e-03]
 [3.54753840e-01 4.15042586e-04 1.79212748e-04 8.21894846e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.34137891e-03 1.53927373e-04 3.53657137e-05 2.20657642e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.88284792e-05 4.27142789e-05 1.27784225e-03 4.57702338e-01]
 [1.68819639e-03 3.27430502e-01 6.95319624e-04 1.11504749e-03]
 [2.00495854e-01 4.79798298e-04 1.81336050e-04 1.80584434e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.01607395e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.68949898e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.